### ISSUE TITLE
Blank Details box during Analyze

### ISSUE THREAD

**Issue by bekahuber** [ABCD-STUDY/DEAP#45] opened 2018-10-22 23:07 UTC
Using firefox browser on a Mac desktop, after running analyses there is a blank box (Details last used items) that appears in the results.  I am not able to close the box and it doesn't have any information. 

<img width="1879" alt="screen shot 2018-10-22 at 5 03 35 pm" src="https://user-images.githubusercontent.com/44382670/47324349-a75b3180-d61c-11e8-86d1-6fdc68690406.png">

**Comment by HaukeBartsch** [comment] 2018-10-23 16:07
I have seen something similar after changing variables. I suggest to add a 'X' in the upper right corner of the floating dialog to allow people to close it.

**Comment by HaukeBartsch** [comment] 2018-10-23 16:50
This was caused by a combination of click on variables in the input boxes and closing of boxes in the dialog using the 'x'. There is code there now that checks if all entries are empty. Should be fixed now on abcd-deap.

**Closed** 2018-10-23 16:52 UTC
Labels: bug
