### ISSUE TITLE
sports and activities questionnaire

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#31] opened 2018-10-20 02:01 UTC
In the sports and activities questionnaire there is a logical flow to the questions so if you answer “Does your child read for pleasure?” as NO you do not see the next question which is “How many hours per week does your child read?”.  Therefore in the latter variable (sports_activity_read_hours_p) there is a large number of NAs who said NO to the previous question although for analyses it would be more informative if these were coded as 0 hours per week.  Hope that makes sense!  Currently when you run a model in DEAP with this variable it just excludes about 1000 subjects from the analysis who are coded as NA rather than including them as 0 hours.

**Comment by HaukeBartsch** [comment] 2018-10-20 04:01
Our internal workflow is to create a scored version of the same instrument. In that version we replace the NA values caused by branching logic with 0. That scoring instrument can also be used to add summary scores. Look for variables that have _ss_ in the name. I believe the sai instrument is already on the list of instruments that will get summary scores in the next data release.

For now it is easiest to replace the NA values in the Scores application with 0. Let me know if you need an example on how this would look like.

**Comment by cpalmer14** [comment] 2018-10-22 15:53
Perfect - thanks Hauke

**Comment by HaukeBartsch** [comment] 2018-10-28 20:30
I will close this issue for now, we should revisit this for the next release (2.0)

**Closed by HaukeBartsch** 2018-10-28 20:30 UTC
Labels: Data issue
