### ISSUE TITLE
Transformation box remains visible after toggling off

### ISSUE THREAD

**Issue by chasereuter1** [ABCD-STUDY/DEAP#46] opened 2018-10-23 15:49 UTC
After toggling the transformation box on and off once, if you try to do the same another time, the box will remain open, despite toggling off.

**Comment by HaukeBartsch** [comment] 2018-10-23 16:06
Hi Chase, I tried to reproduce and could not. Please specify your browser and what variables you used. Stick to the default model and let us know the steps.

I opened Analyze on deaptest (Safari) and clicked on the independent variable, I switched on the log transform (turned green) and switch is off again. I afterwards clicked on the dependent variable and repeated the same. It still worked for me.

**Comment by HaukeBartsch** [comment] 2018-10-23 16:48
Is this a duplicate of #45?

**Comment by HaukeBartsch** [comment] 2018-10-23 23:47
Hi Chase, I think I have fixed this issue on our abcd-deap system. Would be good if you can test it tomorrow after deaptest updates. Hopefully its gone now.

**Closed** 2018-10-24 23:00 UTC
